/**
 * Generates src/render/smufl/generated/bravura.ts from fonts/bravura_metadata.json
 * and fonts/glyphnames.json, keeping only glyph families a piano score needs.
 * Run: npm run smufl:gen
 */
import { readFileSync, writeFileSync } from "node:fs";

const meta = JSON.parse(readFileSync("fonts/bravura_metadata.json", "utf8"));
const names = JSON.parse(readFileSync("fonts/glyphnames.json", "utf8"));

const PREFIXES = [
  "notehead", "rest", "flag", "augmentationDot", "accidental", "gClef", "fClef", "cClef",
  "timeSig", "dynamic", "artic", "fermata", "ornament", "keyboardPedal", "arpeggiato",
  "tremolo", "brace", "bracket", "ottava", "repeat", "coda", "segno", "tuplet", "metNote",
  "metAugmentationDot", "barline", "caesura", "breathMark", "stem", "graceNote", "fingering",
  "glissando", "wiggle", "csym", "unpitchedPercussionClef", "octave", "textBlack", "lyrics",
  "note", "clef", "dalSegno", "daCapo", "chant", "systemDivider", "mensural",
];
const EXCLUDE = /^(mensural|chant|noteheadCluster|noteheadSlash|noteheadCircle|noteheadTriangle|noteheadDiamond|noteheadMoon|noteheadRound|noteheadSquare|noteheadPlus|noteheadX|noteheadLarge|noteheadHeavy|noteheadNull|noteheadParenthesis|noteheadSquare|noteShape|accidentalSagittal|accidentalArrow|accidentalBakiye|accidentalBuyuk|accidentalKucuk|accidental[A-Z][a-z]+Komas|wiggleVibrato|wiggleRandom|wiggleSawtooth|wiggleSquare|wiggleCircular|wiggleGlissando|wiggleWavy|wiggleArpeggiato|wiggleTrill(Fast|Slow)|csymAccidental|csymAlteration)/;

const keep = Object.keys(names).filter(
  (n) => PREFIXES.some((p) => n.startsWith(p)) && !EXCLUDE.test(n),
);

type Vec = [number, number];
const glyphs: Record<string, { cp: number; bbox?: { ne: Vec; sw: Vec }; anchors?: Record<string, Vec>; adv?: number }> = {};
for (const n of keep) {
  const cp = parseInt(names[n].codepoint.replace("U+", ""), 16);
  const bb = meta.glyphBBoxes[n];
  const an = meta.glyphsWithAnchors[n];
  const adv = meta.glyphAdvanceWidths[n];
  glyphs[n] = {
    cp,
    ...(bb ? { bbox: { ne: bb.bBoxNE, sw: bb.bBoxSW } } : {}),
    ...(an ? { anchors: an } : {}),
    ...(adv !== undefined ? { adv } : {}),
  };
}

const out = `// GENERATED by scripts/gen-smufl.ts — do not edit by hand.
// Source: Bravura ${meta.fontVersion} metadata (SIL OFL) + SMuFL glyphnames.json.
// Units: staff spaces. bbox = {ne: [x,y], sw: [x,y]}, y up.
import type { SmuflFontData } from "../types";

export const BRAVURA: SmuflFontData = {
  fontName: ${JSON.stringify(meta.fontName)},
  fontVersion: ${JSON.stringify(String(meta.fontVersion))},
  engravingDefaults: ${JSON.stringify(Object.fromEntries(Object.entries(meta.engravingDefaults).filter(([, v]) => typeof v === "number")))},
  glyphs: ${JSON.stringify(glyphs)},
};

export type BravuraGlyphName = keyof typeof BRAVURA.glyphs;
`;
writeFileSync("src/render/smufl/generated/bravura.ts", out);
console.log(`kept ${keep.length} glyphs`);
